name: CI

on:
  push:
    branches:
      - master
      - major
      - stable
      - release*
    tags:
      - 4.*
  pull_request:
    branches:
      - master
      - major

jobs:
  test:
    name: CKEditor 4 ${{ matrix.type }} on ${{ matrix.browser }}
    strategy:
      matrix:
        type: [ 'dev', 'built' ]
        browser: [ 'Chrome' ]
    runs-on: windows-latest
    steps:
      # https://stackoverflow.com/questions/58033366/how-to-get-current-branch-within-github-actions
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - uses: actions/checkout@v1
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 10
      - run: npm install
      - run: npm install benderjs-cli -g
      - run: sh -e ./dev/travis/build.sh $BRANCH && BUILD_PATH="$(sh -e ./dev/travis/buildpath.sh) && cd $BUILD_PATH"
        shell: bash
        env:
          BRANCH: ${{ steps.extract_branch.outputs.branch }}
        if: matrix.type == 'built' && (steps.extract_branch.outputs.branch == 'master' || steps.extract_branch.outputs.branch == 'major')
      - run: bender run -c bender.ci.js
        env:
          BROWSER: ${{ matrix.browser }}
