name: CI

on:
  push:
    branches:
      - master
      - major
      - stable
      - release*
    tags:
      - 4.*
  pull_request:
    branches:
      - master
      - major

jobs:
  test:
    name: CKEditor 4 ${{ matrix.type }}
    strategy:
      matrix:
        type: [ 'dev', 'built' ]
        browser: [ 'Chrome' ]
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 10
      - run: npm install
      - run: npm install benderjs-cli -g
      - run: sh -e ./dev/travis/build.sh ${GITHUB_REF#refs/heads/} && BUILD_PATH="$(sh -e ./dev/travis/buildpath.sh) && cd $BUILD_PATH"
        if: matrix.type == 'built'
      - run: bender run -c bender.ci.js
        env:
          BROWSER: ${{ matrix.browser }}
